#!/bin/bash
#
# Init file for perfSONAR Lookup Service Cache Daemon
#
# chkconfig: 2345 60 20
# description: perfSONAR Lookup Service Cache Daemon
#

PREFIX=/opt/perfsonar_ps/ls_cache_daemon
BINDIR=${PREFIX}/bin
CONFDIR=${PREFIX}/etc
RUNDIR=/var/run

CONFFILE=${CONFDIR}/ls_cache_daemon.conf
LOGGERFILE=${CONFDIR}/ls_cache_daemon-logger.conf
PIDFILE=${RUNDIR}/ls_cache_daemon.pid

USER=perfsonar
GROUP=perfsonar

PERFSONAR="${BINDIR}/daemon.pl --config=${CONFFILE} --pidfile=${PIDFILE} --logger=${LOGGERFILE} --user=${USER} --group=${GROUP}"

ERROR=0
ARGV="$@"
if [ "x$ARGV" = "x" ] ; then 
    ARGS="help"
fi

for ARG in $@ $ARGS
do
    # check for pidfile
    if [ -f $PIDFILE ] ; then
        PID=`cat $PIDFILE`
        if [ "x$PID" != "x" ] && kill -0 $PID 2>/dev/null ; then
            STATUS="LS Cache Daemon (pid $PID) running"
            RUNNING=1
        else
            STATUS="LS Cache Daemon (pid $PID?) not running"
            RUNNING=0
        fi
    else
        STATUS="LS Cache Daemon (no pid file) not running"
        RUNNING=0
    fi 

    case $ARG in
    start)
	echo $PERFSONAR

	if $PERFSONAR ; then
	    echo "$0 $ARG: LS Cache Daemon started"
	else
	    echo "$0 $ARG: LS Cache Daemon could not be started"
	    ERROR=3
	fi
	;;
    stop)
	if [ $RUNNING -eq 0 ]; then
	    echo "$0 $ARG: $STATUS"
	    continue
	fi
	if kill $PID ; then
	    echo "$0 $ARG: LS Cache Daemon stopped"
	else
	    echo "$0 $ARG: LS Cache Daemon could not be stopped"
	    ERROR=4
	fi
	;;
    restart)
    	$0 stop; echo "waiting..."; sleep 10; $0 start;
	;;
    *)
	echo "usage: $0 (start|stop|restart|help)"
	cat <<EOF

start      - start LS Cache Daemon
stop       - stop LS Cache Daemon
restart    - restart LS Cache Daemon if running by sending a SIGHUP or start if 
             not running
help       - this screen

EOF
	ERROR=2
    ;;

    esac

done

exit $ERROR
